Set up a "Hello Microverse" project
edubew/Hello_microverse pull request #1
Opened 2022-02-08 14:35 UTC by edubew

### Linters installation
**In this milestone, I was able to:**

- Created hello microverse project
- Installed Linters
- Created HTML file, CSS file, and test.md file and ignored the test.md file
- Modified the README file

2022-02-08 15:02 UTC, Deepakdanger requested changes
Hi @edubew, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- Good PR ✔️ 
- Good commit ✔️ 
- No linter error ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-08 15:02 UTC, Deepakdanger commented on index.html
> +    <title>Hello Microverse!</title>
- [ ] **Required** Let's add the `CSS` file link here so that the CSS code will reflect here.

2022-02-10 15:46 UTC, edubew commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/ winfred edube)
Hello ShoiraTa, How is the link supposed to be? I checked it before requesting a review and it still isn't correct.

2022-02-10 18:43 UTC, ShoiraTa commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/ winfred edube)
Hi, Please check your linkedin, you should have the link to your profile there. go to your profile then copy the url, this is my example:
<img width="740" alt="Screenshot 2022-02-10 at 22 42 46" src="https://user-images.githubusercontent.com/77038610/153475089-38ddd1a1-10bb-4f01-b2a8-da8255743b04.png">
 As you can see, my url is `https://www.linkedin.com/in/shoira-ta/`

2022-02-12 09:27 UTC, Whoistolu commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/ winfred edube)
👍🏽 All good now.

2022-02-12 09:28 UTC, Whoistolu approved these changes
### Hi @edubew,

Your project is complete!  There is nothing else to say other than... It's time to merge.

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-12 10:25 UTC, merged